// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TweetFlow.EF;

namespace TweetFlow.EF.Migrations
{
    [DbContext(typeof(TweetFlowContext))]
    [Migration("20180218213525_StreamInfo_EventType")]
    partial class StreamInfo_EventType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TweetFlow.DatabaseModel.TWStreamInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EventType");

                    b.Property<string>("ExceptionMessage");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason");

                    b.HasKey("Id");

                    b.ToTable("TWStreamInfo");
                });

            modelBuilder.Entity("TweetFlow.DatabaseModel.TWUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HashtagBannCount");

                    b.Property<long>("TwitterId");

                    b.Property<int>("WordBannCount");

                    b.HasKey("Id");

                    b.ToTable("TWUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
